/**
 * Place-name gazetteer for the prompt parser.
 *
 * These are exactly the 26 counties and 194 towns used by the Phase 2 dataset
 * generator (`scripts/generate-dataset.ts`), so a name matched here is always a
 * name that exists in `src/data/listings.json`. The list is static reference
 * data, checked in rather than derived at runtime, so `parse.ts` stays
 * independent of the dataset file.
 *
 * Eleven town names are also county names (Carlow, Cavan, Kildare, Kilkenny,
 * Longford, Monaghan, Roscommon, Sligo, Tipperary, Wexford, Wicklow) — the
 * parser resolves that ambiguity, see `resolvePlace` in `parse.ts`.
 */

export interface GazetteerTown {
  name: string;
  county: string;
}

export const COUNTY_NAMES: readonly string[] = [
  "Carlow",
  "Cavan",
  "Clare",
  "Cork",
  "Donegal",
  "Dublin",
  "Galway",
  "Kerry",
  "Kildare",
  "Kilkenny",
  "Laois",
  "Leitrim",
  "Limerick",
  "Longford",
  "Louth",
  "Mayo",
  "Meath",
  "Monaghan",
  "Offaly",
  "Roscommon",
  "Sligo",
  "Tipperary",
  "Waterford",
  "Westmeath",
  "Wexford",
  "Wicklow",
];

export const TOWN_NAMES: readonly GazetteerTown[] = [
  { name: "Abbeyleix", county: "Laois" },
  { name: "Adare", county: "Limerick" },
  { name: "Ardee", county: "Louth" },
  { name: "Arklow", county: "Wicklow" },
  { name: "Ashbourne", county: "Meath" },
  { name: "Athenry", county: "Galway" },
  { name: "Athlone", county: "Westmeath" },
  { name: "Athy", county: "Kildare" },
  { name: "Bagenalstown", county: "Carlow" },
  { name: "Balbriggan", county: "Dublin" },
  { name: "Ballaghaderreen", county: "Roscommon" },
  { name: "Ballina", county: "Mayo" },
  { name: "Ballinamore", county: "Leitrim" },
  { name: "Ballinasloe", county: "Galway" },
  { name: "Ballincollig", county: "Cork" },
  { name: "Ballinrobe", county: "Mayo" },
  { name: "Ballybay", county: "Monaghan" },
  { name: "Ballybofey", county: "Donegal" },
  { name: "Ballyhaunis", county: "Mayo" },
  { name: "Ballymahon", county: "Longford" },
  { name: "Ballymote", county: "Sligo" },
  { name: "Ballyshannon", county: "Donegal" },
  { name: "Banagher", county: "Offaly" },
  { name: "Bandon", county: "Cork" },
  { name: "Bantry", county: "Cork" },
  { name: "Belmullet", county: "Mayo" },
  { name: "Belturbet", county: "Cavan" },
  { name: "Bettystown", county: "Meath" },
  { name: "Birr", county: "Offaly" },
  { name: "Blackrock", county: "Dublin" },
  { name: "Blanchardstown", county: "Dublin" },
  { name: "Blarney", county: "Cork" },
  { name: "Blessington", county: "Wicklow" },
  { name: "Borris", county: "Carlow" },
  { name: "Boyle", county: "Roscommon" },
  { name: "Bray", county: "Wicklow" },
  { name: "Bunclody", county: "Wexford" },
  { name: "Buncrana", county: "Donegal" },
  { name: "Bundoran", county: "Donegal" },
  { name: "Cahersiveen", county: "Kerry" },
  { name: "Cahir", county: "Tipperary" },
  { name: "Callan", county: "Kilkenny" },
  { name: "Carlingford", county: "Louth" },
  { name: "Carlow", county: "Carlow" },
  { name: "Carrick-on-Shannon", county: "Leitrim" },
  { name: "Carrick-on-Suir", county: "Tipperary" },
  { name: "Carrickmacross", county: "Monaghan" },
  { name: "Carrigaline", county: "Cork" },
  { name: "Cashel", county: "Tipperary" },
  { name: "Castlebar", county: "Mayo" },
  { name: "Castleblayney", county: "Monaghan" },
  { name: "Castlecomer", county: "Kilkenny" },
  { name: "Castleconnell", county: "Limerick" },
  { name: "Castleisland", county: "Kerry" },
  { name: "Castleknock", county: "Dublin" },
  { name: "Castlepollard", county: "Westmeath" },
  { name: "Castlerea", county: "Roscommon" },
  { name: "Cavan", county: "Cavan" },
  { name: "Celbridge", county: "Kildare" },
  { name: "Clane", county: "Kildare" },
  { name: "Clara", county: "Offaly" },
  { name: "Claremorris", county: "Mayo" },
  { name: "Clifden", county: "Galway" },
  { name: "Clogherhead", county: "Louth" },
  { name: "Clonakilty", county: "Cork" },
  { name: "Clondalkin", county: "Dublin" },
  { name: "Clones", county: "Monaghan" },
  { name: "Clonmel", county: "Tipperary" },
  { name: "Clontarf", county: "Dublin" },
  { name: "Cobh", county: "Cork" },
  { name: "Collooney", county: "Sligo" },
  { name: "Cootehill", county: "Cavan" },
  { name: "Cork City", county: "Cork" },
  { name: "Courtown", county: "Wexford" },
  { name: "Delgany", county: "Wicklow" },
  { name: "Dingle", county: "Kerry" },
  { name: "Donegal Town", county: "Donegal" },
  { name: "Drogheda", county: "Louth" },
  { name: "Drumcondra", county: "Dublin" },
  { name: "Drumlish", county: "Longford" },
  { name: "Drumshanbo", county: "Leitrim" },
  { name: "Dun Laoghaire", county: "Dublin" },
  { name: "Dunboyne", county: "Meath" },
  { name: "Dundalk", county: "Louth" },
  { name: "Dundrum", county: "Dublin" },
  { name: "Dungarvan", county: "Waterford" },
  { name: "Dunleer", county: "Louth" },
  { name: "Dunmore East", county: "Waterford" },
  { name: "Dunshaughlin", county: "Meath" },
  { name: "Edenderry", county: "Offaly" },
  { name: "Edgeworthstown", county: "Longford" },
  { name: "Enfield", county: "Meath" },
  { name: "Ennis", county: "Clare" },
  { name: "Enniscorthy", county: "Wexford" },
  { name: "Ennistymon", county: "Clare" },
  { name: "Fermoy", county: "Cork" },
  { name: "Galway City", county: "Galway" },
  { name: "Gorey", county: "Wexford" },
  { name: "Gort", county: "Galway" },
  { name: "Graiguenamanagh", county: "Kilkenny" },
  { name: "Granard", county: "Longford" },
  { name: "Greystones", county: "Wicklow" },
  { name: "Howth", county: "Dublin" },
  { name: "Kells", county: "Meath" },
  { name: "Kenmare", county: "Kerry" },
  { name: "Kilcoole", county: "Wicklow" },
  { name: "Kildare", county: "Kildare" },
  { name: "Kilkee", county: "Clare" },
  { name: "Kilkenny", county: "Kilkenny" },
  { name: "Killarney", county: "Kerry" },
  { name: "Killorglin", county: "Kerry" },
  { name: "Kilmacthomas", county: "Waterford" },
  { name: "Kilmallock", county: "Limerick" },
  { name: "Kilrush", county: "Clare" },
  { name: "Kingscourt", county: "Cavan" },
  { name: "Kinnegad", county: "Westmeath" },
  { name: "Kinsale", county: "Cork" },
  { name: "Leighlinbridge", county: "Carlow" },
  { name: "Leixlip", county: "Kildare" },
  { name: "Letterkenny", county: "Donegal" },
  { name: "Lifford", county: "Donegal" },
  { name: "Limerick City", county: "Limerick" },
  { name: "Listowel", county: "Kerry" },
  { name: "Longford", county: "Longford" },
  { name: "Loughrea", county: "Galway" },
  { name: "Lucan", county: "Dublin" },
  { name: "Lusk", county: "Dublin" },
  { name: "Macroom", county: "Cork" },
  { name: "Malahide", county: "Dublin" },
  { name: "Mallow", county: "Cork" },
  { name: "Manorhamilton", county: "Leitrim" },
  { name: "Maynooth", county: "Kildare" },
  { name: "Midleton", county: "Cork" },
  { name: "Mitchelstown", county: "Cork" },
  { name: "Moate", county: "Westmeath" },
  { name: "Mohill", county: "Leitrim" },
  { name: "Monaghan", county: "Monaghan" },
  { name: "Monasterevin", county: "Kildare" },
  { name: "Mountmellick", county: "Laois" },
  { name: "Mountrath", county: "Laois" },
  { name: "Mullingar", county: "Westmeath" },
  { name: "Naas", county: "Kildare" },
  { name: "Navan", county: "Meath" },
  { name: "Nenagh", county: "Tipperary" },
  { name: "New Ross", county: "Wexford" },
  { name: "Newbridge", county: "Kildare" },
  { name: "Newcastle West", county: "Limerick" },
  { name: "Newtownmountkennedy", county: "Wicklow" },
  { name: "Oranmore", county: "Galway" },
  { name: "Portarlington", county: "Laois" },
  { name: "Portlaoise", county: "Laois" },
  { name: "Portlaw", county: "Waterford" },
  { name: "Portumna", county: "Galway" },
  { name: "Rathdrum", county: "Wicklow" },
  { name: "Rathkeale", county: "Limerick" },
  { name: "Rathmines", county: "Dublin" },
  { name: "Rathnew", county: "Wicklow" },
  { name: "Ratoath", county: "Meath" },
  { name: "Roscommon", county: "Roscommon" },
  { name: "Roscrea", county: "Tipperary" },
  { name: "Rosslare", county: "Wexford" },
  { name: "Rush", county: "Dublin" },
  { name: "Sallins", county: "Kildare" },
  { name: "Salthill", county: "Galway" },
  { name: "Sandyford", county: "Dublin" },
  { name: "Shannon", county: "Clare" },
  { name: "Sixmilebridge", county: "Clare" },
  { name: "Skerries", county: "Dublin" },
  { name: "Skibbereen", county: "Cork" },
  { name: "Slane", county: "Meath" },
  { name: "Sligo", county: "Sligo" },
  { name: "Strandhill", county: "Sligo" },
  { name: "Strokestown", county: "Roscommon" },
  { name: "Swinford", county: "Mayo" },
  { name: "Swords", county: "Dublin" },
  { name: "Tallaght", county: "Dublin" },
  { name: "Templemore", county: "Tipperary" },
  { name: "Terenure", county: "Dublin" },
  { name: "Thomastown", county: "Kilkenny" },
  { name: "Thurles", county: "Tipperary" },
  { name: "Tipperary", county: "Tipperary" },
  { name: "Tralee", county: "Kerry" },
  { name: "Tramore", county: "Waterford" },
  { name: "Trim", county: "Meath" },
  { name: "Tuam", county: "Galway" },
  { name: "Tubbercurry", county: "Sligo" },
  { name: "Tullamore", county: "Offaly" },
  { name: "Tullow", county: "Carlow" },
  { name: "Virginia", county: "Cavan" },
  { name: "Waterford City", county: "Waterford" },
  { name: "Westport", county: "Mayo" },
  { name: "Wexford", county: "Wexford" },
  { name: "Wicklow", county: "Wicklow" },
  { name: "Youghal", county: "Cork" },
];
